Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", ip: "192.168.33.11"
  config.vm.network "private_network", ip: "192.168.33.12"
  config.vm.network "private_network", ip: "192.168.33.13"

  config.vm.synced_folder "./src", "/home/vagrant/src", id: "core1", :nfs => true, :mount_options => ['nolock,vers=3,udp']
  config.vm.synced_folder "./dbbackup", "/home/vagrant/dbbackup", id: "core2", :nfs => true, :mount_options => ['nolock,vers=3,udp']

  config.vm.provider :virtualbox do |vb|

    vb.memory = 4096
  end
  config.vm.provision "docker"

  # 初回起動時
  config.vm.provision "shell", inline: <<-SHELL
  test -f /etc/bootstrapped && exit
    # http://qiita.com/spesnova/items/018b74ea1cc0a9e8787d
    sudo timedatectl set-timezone Asia/Tokyo

    sudo apt-get -y install language-pack-ja-base language-pack-ja
    localectl set-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"
    sudo apt install docker-compose -y

  date > /etc/bootstrapped
  SHELL
end
