Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu16.04"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", ip: "192.168.33.11"
  config.vm.network "private_network", ip: "192.168.33.12"
  config.vm.network "private_network", ip: "192.168.33.13"

  config.vm.synced_folder "../src", "/home/vagrant/src", id: "core1", :nfs => true, :mount_options => ['nolock,vers=3,udp']
  config.vm.synced_folder "../dbbackup", "/home/vagrant/dbbackup", id: "core2", :nfs => true, :mount_options => ['nolock,vers=3,udp']
  
  config.vm.provider :virtualbox do |vb|

    vb.memory = 4096
  end
  config.vm.provision "docker"

  # 初回起動時
  config.vm.provision "shell", inline: <<-SHELL
  test -f /etc/bootstrapped && exit
    # http://qiita.com/koara-local/items/ee887bab8c7186d00a88
    # sudo apt-get update
    # sudo apt-get install apt-transport-https ca-certificates
    # sudo apt-key adv \
    #            --keyserver hkp://ha.pool.sks-keyservers.net:80 \
    #            --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    # echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list
    # sudo apt-get update
    # sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual
    # sudo apt-get update
    # sudo apt-get install docker-engine
    # sudo service docker start

    # http://qiita.com/spesnova/items/018b74ea1cc0a9e8787d
    sudo timedatectl set-timezone Asia/Tokyo

    sudo apt-get -y install language-pack-ja-base language-pack-ja
    localectl set-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"
    sudo apt install docker-compose -y
    
  date > /etc/bootstrapped
  SHELL
end
